// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0omuZHLdY7BzMjG5IdqaH06g6BBMLzG8',
    appId: '1:284660955276:web:80c85388b189eee1b263a9',
    messagingSenderId: '284660955276',
    projectId: 'zainab-restuarant',
    authDomain: 'zainab-restuarant.firebaseapp.com',
    storageBucket: 'zainab-restuarant.firebasestorage.app',
    measurementId: 'G-4LNGTKTDQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo3pgKaSvdFPVyhJ_YxkM8JW0m--JVoSo',
    appId: '1:284660955276:android:0d6e5f767fef020eb263a9',
    messagingSenderId: '284660955276',
    projectId: 'zainab-restuarant',
    storageBucket: 'zainab-restuarant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnApnmUmmhaO9PKfxJ_Qgf-Ny347Y5C8M',
    appId: '1:284660955276:ios:72dc3edb6dd3537bb263a9',
    messagingSenderId: '284660955276',
    projectId: 'zainab-restuarant',
    storageBucket: 'zainab-restuarant.firebasestorage.app',
    iosBundleId: 'com.example.zainabRestuarantApp',
  );
}
